name: Secure Proxy Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
# Updated to trigger schedule
jobs:
  run-secure-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run Secure Proxy Bot
        run: php proxybot_secure.php
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }} 
# force schedule reactivate
